### ISSUE TITLE
Unable to create reminders with date within [[link]]

### ISSUE THREAD

**Issue by rushikb** [uphy/obsidian-reminder#22]
Thank you for this plugin— its incredibly useful. I tend to use dates within [[]] links wherever possible in order to ensure that tasks can also be back-linked to the right day. Is there a way to change settings in order to support this?

**Comment by uphy** [comment]
I'm glad you like.
Can you give me an example input and expected reminder?

For example,

input:

```
- [ ] foo (@2021-09-10)
```

expected reminder:
- title: foo
- due date: 2021/09/10

**Comment by rushikb** [comment]
Sure— What I mean is 
` - [  ]  foo (@[[2021-09-10]] 14:55)`

The advantage of this is that is ensures that all dates can also be backlinked to the daily notes page

**Comment by dcoales** [comment]
I'm also using the Kanban board with the option turned on to link dates to journal pages.  The resulting date format is 

@[[YYYY-MM-DD]]

Because I've chosen YYYY-MM-DD as the date format within the Kanban settings.  I think time formats are set using the following formats

@@HH:MM

Currently this date format isn't recognised by reminder even with the enable kanban format toggle enabled.  I realise this might be tricky to implement generically as Kanban allows you to change not only the date format but also the date and time triggers (e.g. from @ and @@ to anything else).

**Comment by uphy** [comment]
@rushikb Thank you.  I will consider implementing it.

@dcoales I didn't know that! Current implementation uses `@` for date and `@@` for time trigger.  Also their format must be YYYY-MM-DD , HH:mm.
I will consider to use Kanban plugin's format in the setting.

**Comment by dcoales** [comment]
Thank you very much.

**Comment by uphy** [comment]
@rushikb Supported in v1.1.0.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/1233373/133252293-806932f5-af9f-41c2-bcff-4fbb43867b6b.png">

**Comment by uphy** [comment]
@dcoales  Supported in v1.1.0.

**Comment by rushikb** [comment]
Thank you! this is amazing!

**Comment by dcoales** [comment]
Hi,

As part of this change, could Kanban dates in the format @[[YYYY-MM-DD]] be supported.  I have tried turning on both Kanban support and linking to dates in the options but this still doesn't recognise Kanban dates when they too are links to dates.

Many thanks,
David

**Comment by uphy** [comment]
> I have tried turning on both Kanban support and linking to dates in the options but this still doesn't recognise Kanban dates when they too are links to dates.

It is not reproduced for me.  Maybe you need a restart.
If you have problems again, please open again.
