### ISSUE TITLE
bring obsidian to the front at the time of the reminder

### ISSUE THREAD

**Issue by imed-ghomari** [uphy/obsidian-reminder#5]
I am leaving obsidian open and hidden most of the time, so it would be nice if you could bring the obsidian window to the front when the reminder is fired. I don't know if it's easier, but I believe this is an alternative to the system notification support, no ?

**Comment by uphy** [comment]
@imeed166 @wenlzhang Can you check v1.0.3?
I've implemented system notification feature roughly.
Please check `Use system notification`.

<img width="1585" alt="image" src="https://user-images.githubusercontent.com/1233373/131272416-33af4819-1edc-4cb0-9222-15b93b2943fc.png">

**Comment by Cito** [comment]
Really useful feature. Just tested this on Windows 10, works great!

**Comment by imeed166** [comment]
Yes @uphy it works great, thank you. But if I use system notification, I can't postpone the task. So 2 solutions comes to mind : 
- implement a native way to postpone the reminder with the option specified in the plugin settings
- keep both system notification and obsidian notification enabled, so that when I get a reminder, I can postpone it by opening obsidian.
![image](https://user-images.githubusercontent.com/38974541/131307613-6535841d-a67d-4ede-a915-ee34b691639f.png)
![image](https://user-images.githubusercontent.com/38974541/131320720-85119952-1e7e-4670-8a07-878eba59c59d.png)

**Comment by uphy** [comment]
@imeed166 When you click the notification (not close button, left part of the it), an reminder modal should be seen in Obsidian.
In the modal, you can postpone the task as you did before.
(maybe solution 2)

Also, the Later options in the system notification is possible only in Mac. (the API seems not available on Windows)
I can implement it in the future 👍🏼

**Comment by imeed166** [comment]
I see, perfect, solution 2 is already here. Yes, a mac specific implementation would be nice, but I think that it's already very functional as it is, so I think you should focus on other more urgent issues for now. Thank you again for this great plugin.

**Comment by uphy** [comment]
I'm glad to hear that.
Thank you for suggesting cool features!

**Comment by uphy** [comment]
I close this issue.
Instead, I create another issue for supporting system notification actions.

**Comment by wenlzhang** [comment]
Thank you, @uphy , for implementing this! It works like a charm!
