### ISSUE TITLE
[Feature]: Recurring reminders

### ISSUE THREAD

**Issue by DenisVCode** [uphy/obsidian-reminder#50]
### Goal or desired outcome of this feature

Ability to schedule repeated and recurring tasks and reminders.

Thank you for your work, I have just started using your plugin and it's useful!

### Describe the feature

It would be useful to schedule recurring reminders for regular tasks. 
Examples 
- Run backup @weekly
- Workout @daily

The syntax used for cron schedule expressions could be used for scheduling exactly to one's needs.

I could see history being generated below each item, based on if the item was completed that time or not, but that might not be super useful for everyone, for example:
- [ ] Workout (@daily)
   - 3.1.2022 - Done
   - 4.1.2022 - Missed
   - 5.1.2022 - Done

(Each check-in workout would generate a new line and then reset back to an unchecked state)

**Comment by uphy** [comment]
Thank you for your suggestion!

You can use Tasks Plugin integration feature.

related:
- https://uphy.github.io/obsidian-reminder/guide/interop-tasks.html
- https://github.com/uphy/obsidian-reminder/issues/35
- https://github.com/uphy/obsidian-reminder/issues/17

I want to focus on the reminder feature in this plugin; the recurring feature is considered to be a category of task management, not a reminder.
In order to avoid making code more complicated than they need to be, I would like to solve this problem by using [Tasks Plugin](https://github.com/schemar/obsidian-tasks) .

**Comment by DenisVCode** [comment]
That seems like a great solution, thank you, have a great day!
