### ISSUE TITLE
BUG:  Linking from Overdue

### ISSUE THREAD

**Issue by AJP4** [uphy/obsidian-reminder#56]
### Describe the bug

Under the header "overdue" items do not open the linked file.  Other headings like "today", "tomorrow" do link.

### Expected Behavior

Able to link to file with the reminder in it

### Steps to reproduce

Have a task in the past, open up reminder in side panel and click the item

### Operating system

Windows

**Comment by uphy** [comment]
It's expected behavior:

https://github.com/uphy/obsidian-reminder/issues/96

**Comment by CalmDownMonkey** [comment]
What is the expected user action to close an overdue reminder?

The only action I can take is to manually search for the reminder text and find the checkbox myself so I can tick it.

To be clear, for a reminder in the future, this is the process:
- Click the reminder from the reminder panel
- Be taken to the correct file and line where the reminder is
- Tick the checkbox - reminder is complete

For an overdue reminder:
- Don't click the reminder, because that doesn't work (I can see nothing else clickable in the reminder panel)
- Manually search for the file with the reminder in it, and find the reminder
- Tick the checkbox - reminder is complete

What's the rationale for the difference? Are we missing something?
